# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herriak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena_eus', models.CharField(max_length=200)),
                ('izena_cast', models.CharField(max_length=200)),
                ('probintzia', models.CharField(max_length=200)),
            ],
        ),
    ]
